/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioWonderlandRouteImport } from './routes/portfolio/wonderland'
import { Route as PortfolioVogueAfricaRouteImport } from './routes/portfolio/vogue-africa'
import { Route as PortfolioRunwayRouteImport } from './routes/portfolio/runway'
import { Route as PortfolioGraziaRouteImport } from './routes/portfolio/grazia'
import { Route as PortfolioBtsRouteImport } from './routes/portfolio/bts'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWonderlandRoute = PortfolioWonderlandRouteImport.update({
  id: '/portfolio/wonderland',
  path: '/portfolio/wonderland',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioVogueAfricaRoute = PortfolioVogueAfricaRouteImport.update({
  id: '/portfolio/vogue-africa',
  path: '/portfolio/vogue-africa',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRunwayRoute = PortfolioRunwayRouteImport.update({
  id: '/portfolio/runway',
  path: '/portfolio/runway',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioGraziaRoute = PortfolioGraziaRouteImport.update({
  id: '/portfolio/grazia',
  path: '/portfolio/grazia',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioBtsRoute = PortfolioBtsRouteImport.update({
  id: '/portfolio/bts',
  path: '/portfolio/bts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/bts': typeof PortfolioBtsRoute
  '/portfolio/grazia': typeof PortfolioGraziaRoute
  '/portfolio/runway': typeof PortfolioRunwayRoute
  '/portfolio/vogue-africa': typeof PortfolioVogueAfricaRoute
  '/portfolio/wonderland': typeof PortfolioWonderlandRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/bts': typeof PortfolioBtsRoute
  '/portfolio/grazia': typeof PortfolioGraziaRoute
  '/portfolio/runway': typeof PortfolioRunwayRoute
  '/portfolio/vogue-africa': typeof PortfolioVogueAfricaRoute
  '/portfolio/wonderland': typeof PortfolioWonderlandRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/bts': typeof PortfolioBtsRoute
  '/portfolio/grazia': typeof PortfolioGraziaRoute
  '/portfolio/runway': typeof PortfolioRunwayRoute
  '/portfolio/vogue-africa': typeof PortfolioVogueAfricaRoute
  '/portfolio/wonderland': typeof PortfolioWonderlandRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/testimonials'
    | '/portfolio/bts'
    | '/portfolio/grazia'
    | '/portfolio/runway'
    | '/portfolio/vogue-africa'
    | '/portfolio/wonderland'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/testimonials'
    | '/portfolio/bts'
    | '/portfolio/grazia'
    | '/portfolio/runway'
    | '/portfolio/vogue-africa'
    | '/portfolio/wonderland'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/resources'
    | '/services'
    | '/testimonials'
    | '/portfolio/bts'
    | '/portfolio/grazia'
    | '/portfolio/runway'
    | '/portfolio/vogue-africa'
    | '/portfolio/wonderland'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  PortfolioBtsRoute: typeof PortfolioBtsRoute
  PortfolioGraziaRoute: typeof PortfolioGraziaRoute
  PortfolioRunwayRoute: typeof PortfolioRunwayRoute
  PortfolioVogueAfricaRoute: typeof PortfolioVogueAfricaRoute
  PortfolioWonderlandRoute: typeof PortfolioWonderlandRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/wonderland': {
      id: '/portfolio/wonderland'
      path: '/portfolio/wonderland'
      fullPath: '/portfolio/wonderland'
      preLoaderRoute: typeof PortfolioWonderlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/vogue-africa': {
      id: '/portfolio/vogue-africa'
      path: '/portfolio/vogue-africa'
      fullPath: '/portfolio/vogue-africa'
      preLoaderRoute: typeof PortfolioVogueAfricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/runway': {
      id: '/portfolio/runway'
      path: '/portfolio/runway'
      fullPath: '/portfolio/runway'
      preLoaderRoute: typeof PortfolioRunwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/grazia': {
      id: '/portfolio/grazia'
      path: '/portfolio/grazia'
      fullPath: '/portfolio/grazia'
      preLoaderRoute: typeof PortfolioGraziaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/bts': {
      id: '/portfolio/bts'
      path: '/portfolio/bts'
      fullPath: '/portfolio/bts'
      preLoaderRoute: typeof PortfolioBtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  PortfolioBtsRoute: PortfolioBtsRoute,
  PortfolioGraziaRoute: PortfolioGraziaRoute,
  PortfolioRunwayRoute: PortfolioRunwayRoute,
  PortfolioVogueAfricaRoute: PortfolioVogueAfricaRoute,
  PortfolioWonderlandRoute: PortfolioWonderlandRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
